# Generated by Django 4.1.1 on 2024-05-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="user_permissions",
        ),
    ]
