# Generated by Django 4.1.1 on 2024-05-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_vendor_groups_remove_vendor_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="user",
        ),
    ]
